### ISSUE TITLE
Advice

### ISSUE THREAD

**Issue by gzaniolo** [CMU-HKN/CMU-Advice#1]
Pleas finish I would like to know who I should be friends with. Have spent 2 yrs at cmu and made no friends, gotten no jobs, and taken no classes bc I have been waiting for this advice.

**Comment by mikinty** [comment]
Hey, thanks for reaching out. Didn't know anybody was going to look at this repo, so this gives me some motivation to get this to some sort of starting point. Was hoping to open-source this so more people can give their thoughts, but I can start some articles.
The friend one is difficult, I'm not even sure what I originally intend to write about there.
In the meanwhile, you can find some more academic and career-related advice here: https://github.com/mikinty/advice

**Comment by mikinty** [comment]
Ask and you shall receive, happy reading the articles I put up

**Comment by gzaniolo** [comment]
Ebic ty, some fine literature. I can finally continue my CMU career with this knowledge!. 
![image](https://github.com/CMU-HKN/CMU-Advice/assets/99216431/93d4c059-c5c0-4c65-a4d8-7e383f457a26)
